### ISSUE TITLE
Php for header/footer? 

### ISSUE THREAD

**Issue by decodp** [nikitaMihalyov/web-nm#1]
I am a frontend web developer But I learnt a little bit of php. Why dont you use php for header And footer?

Ps: it Very simple :)

**Comment by decodp** [comment]
I like your work

**Comment by nikitaMihalyov** [comment]
Hi. what actually do you mean by using PHP in header and footer?

2016-07-11 21:15 GMT+03:00 decodp <notifications@github.com>:

**Comment by decodp** [comment]
< ?php include 'header.php'; ?>
ALL YOUR CONTENT HERE
< ?php include 'footer.php'; ?>

Header.php 
<html > ....

Footer.php 
</html>

**Comment by nikitaMihalyov** [comment]
I see
But
For what should I use it?

2016-07-12 16:15 GMT+03:00 decodp <notifications@github.com>:

**Comment by decodp** [comment]
For rapidity  :)
One header for every file
One footer for every file
Sorry for My english, if you want I can make a pull request :)
Your site is great  (but I prefer English )

**Comment by nikitaMihalyov** [comment]
Well, I actually include header & footer via Jade (HTML preprocessor) and
it's quiet enough and useful for me

I now don't know PHP at all, but when I start learning it, I'll try to use
your technic, thank you for advice 😉

P.s. I'll try to translate my site into english asap

P.p.s you can also visit my instagram profile if you are interested in:
https://www.instagram.com/nikita.mihalyov/

12 июля 2016 г. 7:33 PM пользователь "decodp" <notifications@github.com>
написал:

**Comment by decodp** [comment]
Thanks!
